# Generated by Django 2.2 on 2020-06-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200606_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
